Write a NumPy program to count a given word in each row of a given array of string values.
Sample output:
Original array of string values:
[['Python' 'NumPy' 'Exercises']
['Python' 'Pandas' 'Exercises']
['Python' 'Machine learning' 'Python']]
Count 'Python' row wise in the above array of string values:
[[1 0 0]
[1 0 0]
[1 0 1]]

In [2]:
import numpy as np

string = np.array([['Python', 'NumPy', 'Exercises'],
                    ['Python', 'Pandas', 'Exercises'],
                    ['Python', 'Machine learning', 'Python']])

print(np.char.count(string, "Python"))

[[1 0 0]
 [1 0 0]
 [1 0 1]]


2nd way of solution:

In [4]:
import numpy as np
a = [['Python', 'NumPy', 'Exercises'],
    ['Python', 'Pandas', 'Exercises'],
    ['Python', 'Machine learning', 'Python']]
b = np.array(a)
b.shape[0]

3

In [5]:
for i in range(b.shape[0]):
    if i == 'Python':
        b[i] = 1
    else:
        b[i] = 0
print(b)

[['0' '0' '0']
 ['0' '0' '0']
 ['0' '0' '0']]


In [3]:
import numpy as np
a = [['Python', 'NumPy', 'Exercises'],
    ['Python', 'Pandas', 'Exercises'],
    ['Python', 'Machine learning', 'Python']]
b = np.array(a)
b.shape[0]
for i in range(b.shape[0]):
    for j in range(b.shape[0]):
        if b[i,j] == 'Python':
            b[i,j] = 1
        else:
            b[i,j] = 0
print(b)

[['1' '0' '0']
 ['1' '0' '0']
 ['1' '0' '1']]


Write a NumPy program to find the set difference of two arrays. The set difference will return the sorted, unique values in array1 that are not in array2.
Expected Output:
Array1: [ 0 10 20 40 60 80]
Array2: [10, 30, 40, 50, 70, 90]
Set difference between two arrays: [ 0 20 60 80]

In [6]:
a = np.array([1, 2, 3, 2, 4, 1])
b = np.array([3, 4, 5, 6])
np.setdiff1d(a, b)


array([1, 2])

In [7]:
arr1 = np.array([ 0, 10, 20, 40, 60, 80])
arr2 = np.array([10, 30, 40, 50, 70, 90])
np.setdiff1d(arr1,arr2)

array([ 0, 20, 60, 80])

Solution with list comprehension:

In [10]:
arr3 = [i for i in arr1 if i not in arr2]
arr3

[0, 20, 60, 80]

Solution with for loop:

In [16]:
arr1 = np.array([ 0, 10, 20, 40, 60, 80])
arr2 = np.array([10, 30, 40, 50, 70, 90])

a = []
for i in arr1:
    if i not in arr2:
        a.append(i)
print(a)


[0, 20, 60, 80]
